rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations:
    - 1
    -
      exclude: ['breakpoint', 'loadlast']

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 1
  no-url-domains: 1

  # Should be enabled as soon as linting options can be turned off for certain files
  # https://github.com/sasstools/sass-lint/issues/70
  no-color-literals: 0

  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 0
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties: 0
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
  attribute-quotes: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 1
  property-units: 0

  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1
  pseudo-element: 0

  # Style Guide
  bem-depth: 0
  border-zero: 1
  brace-style: 1
  clean-import-paths: 1
  empty-args: 0
  hex-length: 1
  hex-notation: 1
  indentation:
    - 1
    -
      size: 4
  leading-zero: 0
  nesting-depth:
  - 1
  -
    max-depth: 3
  property-sort-order: 0
  quotes: 0
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Should be enabled after this bug is fixed https://github.com/sasstools/sass-lint/issues/454
  space-around-operator: 0

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
